SET SCAN OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
EXEC EXEC_SQL_ERGON('ALTER TABLE ERG_TIPOCARGAPREV DISABLE ALL TRIGGERS')
INSERT INTO ERG_TIPOCARGAPREV
(FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, MANUAL, NOME, SIGLA)
SELECT * FROM (
SELECT FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,MANUAL,NOME,SIGLA FROM ERG_TIPOCARGAPREV WHERE 1=0 UNION ALL
SELECT '', '', '', '', '', '', '', '', '', '', 'S', 'DACPREV', 'DACPREV' FROM DUAL
) TEMP_20171127140929
WHERE (SIGLA) NOT IN
  (SELECT SIGLA FROM ERG_TIPOCARGAPREV)
/
COMMIT;
EXEC EXEC_SQL_ERGON('ALTER TABLE ERG_TIPOCARGAPREV ENABLE ALL TRIGGERS')
SET SCAN ON

SET SCAN OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
EXEC EXEC_SQL_ERGON('ALTER TABLE ERG_TIPOCARGAPREV DISABLE ALL TRIGGERS')
INSERT INTO ERG_TIPOCARGAPREV
(FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, MANUAL, NOME, SIGLA)
SELECT * FROM (
SELECT FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,MANUAL,NOME,SIGLA FROM ERG_TIPOCARGAPREV WHERE 1=0 UNION ALL
SELECT '', '', '', '', '', '', '', '', '', '', 'S', 'Não informada', 'Não informada' FROM DUAL
) TEMP_20171127140929
WHERE (SIGLA) NOT IN
  (SELECT SIGLA FROM ERG_TIPOCARGAPREV)
/
COMMIT;
EXEC EXEC_SQL_ERGON('ALTER TABLE ERG_TIPOCARGAPREV ENABLE ALL TRIGGERS')
SET SCAN ON

