SET SCAN OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
EXEC EXEC_SQL_HADES('ALTER TABLE RELATORIOS DISABLE ALL TRIGGERS')
INSERT INTO RELATORIOS
(ARQUIVO, DESCRICAO, DIASEMANA, EH_AGENDAVEL, EH_EXECUTAVEL, EXECUTA_PARAMFORM, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FUNCAO, GRUPO_CODIGO, HORAFIM, HORAINI, LOGGING, NOME, REQUER_GESTOR, SISTEMA)
SELECT * FROM (
<<<<<<< HEAD
SELECT ARQUIVO,DESCRICAO,DIASEMANA,EH_AGENDAVEL,EH_EXECUTAVEL,EXECUTA_PARAMFORM,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FUNCAO,GRUPO_CODIGO,HORAFIM,HORAINI,LOGGING,NOME,REQUER_GESTOR,SISTEMA FROM RELATORIOS WHERE 1=0 UNION ALL
SELECT 'trpvrel0010', 'Inconsistências para concessão da aposentadoria', '', 'N', 'S', 'N', '', '', '', '', '', '', '', '', '', '', '', 'SIGRH-CONCESSAO APOSENT', TO_NUMBER(''), TO_NUMBER(''), 'N', '5FAB4F28C8316E55E050710A5F800DD8', 'N', 'RPrevAposent' FROM DUAL
=======
SELECT ARQUIVO,DESCRICAO,DIASEMANA,EH_AGENDAVEL,EH_EXECUTAVEL,EXECUTA_PARAMFORM,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FUNCAO,GRUPO_CODIGO,HORAFIM,HORAINI,LOGGING,NOME,REQUER_GESTOR,SISTEMA,TIPO_RELAT,TITULO FROM RELATORIOS WHERE 1=0 UNION ALL
SELECT 'trpvrel0010', 'Inconsistências para concessão da aposentadoria', '', 'N', 'S', 'N', '', '', '', '', '', '', '', '', '', '', '', 'SIGRH-CONCESSAO APOSENT', TO_NUMBER(''), TO_NUMBER(''), 'N', '5FAB4F28C8316E55E050710A5F800DD8', 'N', 'RPrevAposent', 'oracle', 'Inconsistências' FROM DUAL
>>>>>>> origin/develop
) TEMP_20171206141908
WHERE (NOME) NOT IN
  (SELECT NOME FROM RELATORIOS)
/
COMMIT;
EXEC EXEC_SQL_HADES('ALTER TABLE RELATORIOS ENABLE ALL TRIGGERS')
SET SCAN ON

SET SCAN OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
EXEC EXEC_SQL_HADES('ALTER TABLE HAD_PARAM_RELAT DISABLE ALL TRIGGERS')
INSERT INTO HAD_PARAM_RELAT
(COD_SQL,  DESCRICAO, NOME_COL_DESC, NOME_COL_VALOR, OBRIGATORIO, ORDEM, PARAMETRO, PROMPT, RELATORIO, SQL_TEXTO, TIPO, TIPO_LOV, TITULO_LOV, VALIDA_LOV, VALOR_DEFAULT)
SELECT * FROM (
SELECT COD_SQL,DESCRICAO,NOME_COL_DESC,NOME_COL_VALOR,OBRIGATORIO,ORDEM,PARAMETRO,PROMPT,RELATORIO,SQL_TEXTO,TIPO,TIPO_LOV,TITULO_LOV,VALIDA_LOV,VALOR_DEFAULT FROM HAD_PARAM_RELAT WHERE 1=0 UNION ALL
SELECT 'DESTYPE', 'Tipo de dispositivo para onde será enviado a saída do relatório', '', '', '', TO_NUMBER('-3'), 'DESTYPE', 'Tipo do destino', '5FAB4F28C8316E55E050710A5F800DD8', '', TO_NUMBER('5'), TO_NUMBER('3'), 'Tipo de Destino do Relatório', '', 'PREVIEW' FROM DUAL
) TEMP_20171206142031
WHERE (PARAMETRO,RELATORIO) NOT IN
  (SELECT PARAMETRO,RELATORIO FROM HAD_PARAM_RELAT)
/
COMMIT;
INSERT INTO HAD_PARAM_RELAT
(COD_SQL,  DESCRICAO, NOME_COL_DESC, NOME_COL_VALOR, OBRIGATORIO, ORDEM, PARAMETRO, PROMPT, RELATORIO, SQL_TEXTO, TIPO, TIPO_LOV, TITULO_LOV, VALIDA_LOV, VALOR_DEFAULT)
SELECT * FROM (
SELECT COD_SQL,DESCRICAO,NOME_COL_DESC,NOME_COL_VALOR,OBRIGATORIO,ORDEM,PARAMETRO,PROMPT,RELATORIO,SQL_TEXTO,TIPO,TIPO_LOV,TITULO_LOV,VALIDA_LOV,VALOR_DEFAULT FROM HAD_PARAM_RELAT WHERE 1=0 UNION ALL
SELECT '', 'Define o nome do arquivo, email ou impressora de acordo com o tipo de destino.', '', '', '', TO_NUMBER('-2'), 'DESNAME', 'Nome do destino', '5FAB4F28C8316E55E050710A5F800DD8', '', TO_NUMBER('5'), TO_NUMBER('0'), '', '', '' FROM DUAL
) TEMP_20171206142031
WHERE (PARAMETRO,RELATORIO) NOT IN
  (SELECT PARAMETRO,RELATORIO FROM HAD_PARAM_RELAT)
/
COMMIT;
INSERT INTO HAD_PARAM_RELAT
(COD_SQL,  DESCRICAO, NOME_COL_DESC, NOME_COL_VALOR, OBRIGATORIO, ORDEM, PARAMETRO, PROMPT, RELATORIO, SQL_TEXTO, TIPO, TIPO_LOV, TITULO_LOV, VALIDA_LOV, VALOR_DEFAULT)
SELECT * FROM (
SELECT COD_SQL,DESCRICAO,NOME_COL_DESC,NOME_COL_VALOR,OBRIGATORIO,ORDEM,PARAMETRO,PROMPT,RELATORIO,SQL_TEXTO,TIPO,TIPO_LOV,TITULO_LOV,VALIDA_LOV,VALOR_DEFAULT FROM HAD_PARAM_RELAT WHERE 1=0 UNION ALL
SELECT 'DESFORMAT', 'Define o formato do arquivo quando o Tipo de destino FILE.', '', '', '', TO_NUMBER('-1'), 'DESFORMAT', 'Formato do Destino', '5FAB4F28C8316E55E050710A5F800DD8', '', TO_NUMBER('5'), TO_NUMBER('3'), 'Formato de destino', '', '' FROM DUAL
) TEMP_20171206142031
WHERE (PARAMETRO,RELATORIO) NOT IN
  (SELECT PARAMETRO,RELATORIO FROM HAD_PARAM_RELAT)
/
COMMIT;
INSERT INTO HAD_PARAM_RELAT
(COD_SQL,  DESCRICAO, NOME_COL_DESC, NOME_COL_VALOR, OBRIGATORIO, ORDEM, PARAMETRO, PROMPT, RELATORIO, SQL_TEXTO, TIPO, TIPO_LOV, TITULO_LOV, VALIDA_LOV, VALOR_DEFAULT)
SELECT * FROM (
SELECT COD_SQL,DESCRICAO,NOME_COL_DESC,NOME_COL_VALOR,OBRIGATORIO,ORDEM,PARAMETRO,PROMPT,RELATORIO,SQL_TEXTO,TIPO,TIPO_LOV,TITULO_LOV,VALIDA_LOV,VALOR_DEFAULT FROM HAD_PARAM_RELAT WHERE 1=0 UNION ALL
SELECT '', '', 'Nome', 'Número', 'S', TO_NUMBER('1'), 'P_NUMFUNC', 'Número funcional', '5FAB4F28C8316E55E050710A5F800DD8', 'select numero, nome'||CHR(10)||'  from funcionarios'||CHR(10)||' order by 2', TO_NUMBER('6'), TO_NUMBER('1'), 'Funcionários', 'S', '' FROM DUAL
) TEMP_20171206142031
WHERE (PARAMETRO,RELATORIO) NOT IN
  (SELECT PARAMETRO,RELATORIO FROM HAD_PARAM_RELAT)
/
COMMIT;
INSERT INTO HAD_PARAM_RELAT
(COD_SQL,  DESCRICAO, NOME_COL_DESC, NOME_COL_VALOR, OBRIGATORIO, ORDEM, PARAMETRO, PROMPT, RELATORIO, SQL_TEXTO, TIPO, TIPO_LOV, TITULO_LOV, VALIDA_LOV, VALOR_DEFAULT)
SELECT * FROM (
SELECT COD_SQL,DESCRICAO,NOME_COL_DESC,NOME_COL_VALOR,OBRIGATORIO,ORDEM,PARAMETRO,PROMPT,RELATORIO,SQL_TEXTO,TIPO,TIPO_LOV,TITULO_LOV,VALIDA_LOV,VALOR_DEFAULT FROM HAD_PARAM_RELAT WHERE 1=0 UNION ALL
SELECT '', '', 'Tipo de vínculo', 'Vínculo', 'S', TO_NUMBER('2'), 'P_NUMVINC', 'Vínculo funcional', '5FAB4F28C8316E55E050710A5F800DD8', 'select numero,  tipovinc from vinculos where numfunc = :P_NUMFUNC', TO_NUMBER('6'), TO_NUMBER('1'), 'Vínculo', 'S', '' FROM DUAL
) TEMP_20171206142031
WHERE (PARAMETRO,RELATORIO) NOT IN
  (SELECT PARAMETRO,RELATORIO FROM HAD_PARAM_RELAT)
/
COMMIT;
INSERT INTO HAD_PARAM_RELAT
(COD_SQL,  DESCRICAO, NOME_COL_DESC, NOME_COL_VALOR, OBRIGATORIO, ORDEM, PARAMETRO, PROMPT, RELATORIO, SQL_TEXTO, TIPO, TIPO_LOV, TITULO_LOV, VALIDA_LOV, VALOR_DEFAULT)
SELECT * FROM (
SELECT COD_SQL,DESCRICAO,NOME_COL_DESC,NOME_COL_VALOR,OBRIGATORIO,ORDEM,PARAMETRO,PROMPT,RELATORIO,SQL_TEXTO,TIPO,TIPO_LOV,TITULO_LOV,VALIDA_LOV,VALOR_DEFAULT FROM HAD_PARAM_RELAT WHERE 1=0 UNION ALL
SELECT '', '', '', '', 'N', TO_NUMBER('3'), 'P_DATA', 'Data base', '5FAB4F28C8316E55E050710A5F800DD8', '', TO_NUMBER('7'), TO_NUMBER('0'), '', 'N', '' FROM DUAL
) TEMP_20171206142031
WHERE (PARAMETRO,RELATORIO) NOT IN
  (SELECT PARAMETRO,RELATORIO FROM HAD_PARAM_RELAT)
/
COMMIT;
EXEC EXEC_SQL_HADES('ALTER TABLE HAD_PARAM_RELAT ENABLE ALL TRIGGERS')
SET SCAN ON
