--
--regras de congelamento de manutenção pré aposentadoria
--
SET SCAN OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
EXEC EXEC_SQL_ERGON('ALTER TABLE TIPO_VANTAGEM_ DISABLE ALL TRIGGERS')
INSERT INTO TIPO_VANTAGEM_
(APARECE_FICHA_FUNCIONAL, APOSENTADORIA, ATIVOS, FALECIDO, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FUNC_DEP, INATIVOS, LIMITE_MANUAL, MANUAL, NOME, OBS, PONTLEI, RUBRICA, SOBREPOE, TIPO, VACANCIA, VANTAGEM)
SELECT * FROM (
SELECT APARECE_FICHA_FUNCIONAL,APOSENTADORIA,ATIVOS,FALECIDO,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FUNC_DEP,INATIVOS,LIMITE_MANUAL,MANUAL,NOME,OBS,PONTLEI,RUBRICA,SOBREPOE,TIPO,VACANCIA,VANTAGEM FROM TIPO_VANTAGEM_ WHERE 1=0 UNION ALL
SELECT 'N', 'N', 'S', 'N', 'N', '', 'N', '', '', 'F', 'N', TO_DATE(''), 'S', 'Congelamento de manutenção pré aposentadoria', '', TO_NUMBER(''), TO_NUMBER(''), 'N', 'Atributo', 'N', 'BLOQUEIO_PRE_APOSENT' FROM DUAL
) TEMP_20171019091440
WHERE (VANTAGEM) NOT IN
  (SELECT VANTAGEM FROM TIPO_VANTAGEM_)
/
COMMIT;
EXEC EXEC_SQL_ERGON('ALTER TABLE TIPO_VANTAGEM_ ENABLE ALL TRIGGERS')
SET SCAN ON
