--
--regras de congelamento de manutenção pré aposentadoria
--
SET SCAN OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
EXEC EXEC_SQL_HADES('ALTER TABLE SISTEMA DISABLE ALL TRIGGERS')
INSERT INTO SISTEMA
(FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, HABILSIS, NOMESIS, SIS, TAKE, VERSAO)
SELECT * FROM (
SELECT FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,HABILSIS,NOMESIS,SIS,TAKE,VERSAO FROM SISTEMA WHERE 1=0 UNION ALL
SELECT '', '', '', '', '', '', '', '', '', '', 'S', 'Concessão de aposentadorias Rio Previdência', 'RPrevAposent', TO_DATE(''), '1.0' FROM DUAL
) TEMP_20171024163231
WHERE (SIS) NOT IN
  (SELECT SIS FROM SISTEMA)
/
COMMIT;
EXEC EXEC_SQL_HADES('ALTER TABLE SISTEMA ENABLE ALL TRIGGERS')
SET SCAN ON

SET SCAN OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
EXEC EXEC_SQL_HADES('ALTER TABLE HAD_OPCOES_GRUPO DISABLE ALL TRIGGERS')
INSERT INTO HAD_OPCOES_GRUPO
(DESCRICAO, GRUPO, SIS)
SELECT * FROM (
SELECT DESCRICAO,GRUPO,SIS FROM HAD_OPCOES_GRUPO WHERE 1=0 UNION ALL
SELECT 'Grupo de opções de dados funcionais', 'DADOS_FUNC', 'RPrevAposent' FROM DUAL
) TEMP_20171019100354
WHERE (SIS,GRUPO) NOT IN
  (SELECT SIS,GRUPO FROM HAD_OPCOES_GRUPO)
/
COMMIT;
EXEC EXEC_SQL_HADES('ALTER TABLE HAD_OPCOES_GRUPO ENABLE ALL TRIGGERS')
SET SCAN ON

SET SCAN OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
EXEC EXEC_SQL_HADES('ALTER TABLE HAD_OPCOES_ITENS DISABLE ALL TRIGGERS')
INSERT INTO HAD_OPCOES_ITENS
(ALIAS_DESCR, ALIAS_VALOR, DESCRICAO, FORMATO, GRUPO, MULTIEMP, OPCAO, SIS, SQL_LISTA, TAMANHO, TIPOALT, TIPO_VALOR, VALMAX, VALMIN, VALOR, VALOR_DEFAULT)
SELECT * FROM (
SELECT ALIAS_DESCR,ALIAS_VALOR,DESCRICAO,FORMATO,GRUPO,MULTIEMP,OPCAO,SIS,SQL_LISTA,TAMANHO,TIPOALT,TIPO_VALOR,VALMAX,VALMIN,VALOR,VALOR_DEFAULT FROM HAD_OPCOES_ITENS WHERE 1=0 UNION ALL
SELECT '', '', 'Atributo para bloqueio de manutenção dos dados pessoais', '', 'DADOS_FUNC', 'N', 'ATRIBUTO_BLOQUEIO', 'RPrevAposent', '', TO_NUMBER('20'), TO_NUMBER('0'), 'V', TO_NUMBER(''), TO_NUMBER(''), 'BLOQUEIO_PRE_APOSENT', '' FROM DUAL
) TEMP_20171019100759
WHERE (SIS,GRUPO,OPCAO) NOT IN
  (SELECT SIS,GRUPO,OPCAO FROM HAD_OPCOES_ITENS)
/
COMMIT;
EXEC EXEC_SQL_HADES('ALTER TABLE HAD_OPCOES_ITENS ENABLE ALL TRIGGERS')
SET SCAN ON
