--
-- Grupos de opções genéricas do módulo de concessão
--

-- Grupo: SIMULACAO
SET SCAN OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
EXEC EXEC_SQL_HADES('ALTER TABLE HAD_OPCOES_GRUPO DISABLE ALL TRIGGERS')
INSERT INTO HAD_OPCOES_GRUPO
(DESCRICAO, GRUPO, SIS)
SELECT * FROM (
SELECT DESCRICAO,GRUPO,SIS FROM HAD_OPCOES_GRUPO WHERE 1=0 UNION ALL
SELECT 'Grupo de opções genéricas para simulação', 'SIMULACAO', 'RPrevAposent' FROM DUAL
) TEMP_20170629162049
WHERE (SIS,GRUPO) NOT IN
  (SELECT SIS,GRUPO FROM HAD_OPCOES_GRUPO)
/
COMMIT;
EXEC EXEC_SQL_HADES('ALTER TABLE HAD_OPCOES_GRUPO ENABLE ALL TRIGGERS')
SET SCAN ON

--GRUPO CONTRIBPRE
SET SCAN OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
EXEC EXEC_SQL_HADES('ALTER TABLE HAD_OPCOES_GRUPO DISABLE ALL TRIGGERS')
INSERT INTO HAD_OPCOES_GRUPO
(DESCRICAO, GRUPO, SIS)
SELECT * FROM (
SELECT DESCRICAO,GRUPO,SIS FROM HAD_OPCOES_GRUPO WHERE 1=0 UNION ALL
SELECT 'Contribuições Previdenciárias', 'CONTRIBPRE', 'RPrevAposent' FROM DUAL
) TEMP_20170906134355
WHERE (SIS,GRUPO) NOT IN
  (SELECT SIS,GRUPO FROM HAD_OPCOES_GRUPO)
/
COMMIT;
EXEC EXEC_SQL_HADES('ALTER TABLE HAD_OPCOES_GRUPO ENABLE ALL TRIGGERS')
SET SCAN ON

--GRUPO RELATORIOS
SET SCAN OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
EXEC EXEC_SQL_HADES('ALTER TABLE HAD_OPCOES_GRUPO DISABLE ALL TRIGGERS')
INSERT INTO HAD_OPCOES_GRUPO
(DESCRICAO, GRUPO, SIS)
SELECT * FROM (
SELECT DESCRICAO,GRUPO,SIS FROM HAD_OPCOES_GRUPO WHERE 1=0 UNION ALL
SELECT 'Grupo de opções para uso em relatórios', 'RELATORIOS', 'RPrevAposent' FROM DUAL
) TEMP_20171117123642
WHERE (SIS,GRUPO) NOT IN
  (SELECT SIS,GRUPO FROM HAD_OPCOES_GRUPO)
/
COMMIT;
EXEC EXEC_SQL_HADES('ALTER TABLE HAD_OPCOES_GRUPO ENABLE ALL TRIGGERS')
SET SCAN ON

--
-- Opções genéricas do módulo de concessão
--

-- Opção: NUM_FOLHA_SIMULACAO (grupo SIMULACAO)
SET SCAN OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
EXEC EXEC_SQL_HADES('ALTER TABLE HAD_OPCOES_ITENS DISABLE ALL TRIGGERS')
INSERT INTO HAD_OPCOES_ITENS
(ALIAS_DESCR, ALIAS_VALOR, DESCRICAO, FORMATO, GRUPO, MULTIEMP, OPCAO, SIS, SQL_LISTA, TAMANHO, TIPOALT, TIPO_VALOR, VALMAX, VALMIN, VALOR, VALOR_DEFAULT)
SELECT * FROM (
SELECT ALIAS_DESCR,ALIAS_VALOR,DESCRICAO,FORMATO,GRUPO,MULTIEMP,OPCAO,SIS,SQL_LISTA,TAMANHO,TIPOALT,TIPO_VALOR,VALMAX,VALMIN,VALOR,VALOR_DEFAULT FROM HAD_OPCOES_ITENS WHERE 1=0 UNION ALL
SELECT '', '', 'Número da folha para simulação de aposentadoria', '', 'SIMULACAO', 'N', 'NUM_FOLHA_SIMULACAO', 'RPrevAposent', '', TO_NUMBER('3'), TO_NUMBER('0'), 'N', TO_NUMBER('999'), TO_NUMBER('1'), '', '' FROM DUAL
) TEMP_20170629162243
WHERE (SIS,GRUPO,OPCAO) NOT IN
  (SELECT SIS,GRUPO,OPCAO FROM HAD_OPCOES_ITENS)
/
COMMIT;
EXEC EXEC_SQL_HADES('ALTER TABLE HAD_OPCOES_ITENS ENABLE ALL TRIGGERS')
SET SCAN ON

-- Opção: TEMPO_LIMITE_SIMULACAO (grupo SIMULACAO)
SET SCAN OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
EXEC EXEC_SQL_HADES('ALTER TABLE HAD_OPCOES_ITENS DISABLE ALL TRIGGERS')
INSERT INTO HAD_OPCOES_ITENS
(ALIAS_DESCR, ALIAS_VALOR, DESCRICAO, FORMATO, GRUPO, MULTIEMP, OPCAO, SIS, SQL_LISTA, TAMANHO, TIPOALT, TIPO_VALOR, VALMAX, VALMIN, VALOR, VALOR_DEFAULT)
SELECT * FROM (
SELECT ALIAS_DESCR,ALIAS_VALOR,DESCRICAO,FORMATO,GRUPO,MULTIEMP,OPCAO,SIS,SQL_LISTA,TAMANHO,TIPOALT,TIPO_VALOR,VALMAX,VALMIN,VALOR,VALOR_DEFAULT FROM HAD_OPCOES_ITENS WHERE 1=0 UNION ALL
SELECT '', '', 'Tempo limite para aguardar o início da simulação (em minutos)', '', 'SIMULACAO', 'N', 'TEMPO_LIMITE_SIMULACAO', 'RPrevAposent', '', TO_NUMBER('2'), TO_NUMBER('0'), 'N', TO_NUMBER('99'), TO_NUMBER('1'), '', '3' FROM DUAL
) TEMP_20170629162243
WHERE (SIS,GRUPO,OPCAO) NOT IN
  (SELECT SIS,GRUPO,OPCAO FROM HAD_OPCOES_ITENS)
/
COMMIT;
EXEC EXEC_SQL_HADES('ALTER TABLE HAD_OPCOES_ITENS ENABLE ALL TRIGGERS')
SET SCAN ON

SET SCAN OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
EXEC EXEC_SQL_HADES('ALTER TABLE HAD_OPCOES_ITENS DISABLE ALL TRIGGERS')
INSERT INTO HAD_OPCOES_ITENS
(ALIAS_DESCR, ALIAS_VALOR, DESCRICAO, FORMATO, GRUPO, MULTIEMP, OPCAO, SIS, SQL_LISTA, TAMANHO, TIPOALT, TIPO_VALOR, VALMAX, VALMIN, VALOR, VALOR_DEFAULT)
SELECT * FROM (
SELECT ALIAS_DESCR,ALIAS_VALOR,DESCRICAO,FORMATO,GRUPO,MULTIEMP,OPCAO,SIS,SQL_LISTA,TAMANHO,TIPOALT,TIPO_VALOR,VALMAX,VALMIN,VALOR,VALOR_DEFAULT FROM HAD_OPCOES_ITENS WHERE 1=0 UNION ALL
SELECT '', '', 'Atributo por opção de não opção da contribuição previdenciária', '', 'CONTRIBPRE', 'N', 'ATRNAOCONTRIB', 'RPrevAposent', '', TO_NUMBER('200'), TO_NUMBER('0'), 'V', TO_NUMBER(''), TO_NUMBER(''), '', '' FROM DUAL
) TEMP_20170906134432
WHERE (SIS,GRUPO,OPCAO) NOT IN
  (SELECT SIS,GRUPO,OPCAO FROM HAD_OPCOES_ITENS)
/
COMMIT;
INSERT INTO HAD_OPCOES_ITENS
(ALIAS_DESCR, ALIAS_VALOR, DESCRICAO, FORMATO, GRUPO, MULTIEMP, OPCAO, SIS, SQL_LISTA, TAMANHO, TIPOALT, TIPO_VALOR, VALMAX, VALMIN, VALOR, VALOR_DEFAULT)
SELECT * FROM (
SELECT ALIAS_DESCR,ALIAS_VALOR,DESCRICAO,FORMATO,GRUPO,MULTIEMP,OPCAO,SIS,SQL_LISTA,TAMANHO,TIPOALT,TIPO_VALOR,VALMAX,VALMIN,VALOR,VALOR_DEFAULT FROM HAD_OPCOES_ITENS WHERE 1=0 UNION ALL
SELECT '', '', 'Indica o atributo que aponta se servidor possui ou não opção por não contribuição na competência.', '', 'CONTRIBPRE', 'N', 'OPCAONAOCONTRIB', 'RPrevAposent', '', TO_NUMBER('200'), TO_NUMBER('0'), 'V', TO_NUMBER(''), TO_NUMBER(''), '', '' FROM DUAL
) TEMP_20170906134432
WHERE (SIS,GRUPO,OPCAO) NOT IN
  (SELECT SIS,GRUPO,OPCAO FROM HAD_OPCOES_ITENS)
/
COMMIT;
EXEC EXEC_SQL_HADES('ALTER TABLE HAD_OPCOES_ITENS ENABLE ALL TRIGGERS')
SET SCAN ON

SET SCAN OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
EXEC EXEC_SQL_HADES('ALTER TABLE HAD_OPCOES_ITENS DISABLE ALL TRIGGERS')
INSERT INTO HAD_OPCOES_ITENS
(ALIAS_DESCR, ALIAS_VALOR, DESCRICAO, FORMATO, GRUPO, MULTIEMP, OPCAO, SIS, SQL_LISTA, TAMANHO, TIPOALT, TIPO_VALOR, VALMAX, VALMIN, VALOR, VALOR_DEFAULT)
SELECT * FROM (
SELECT ALIAS_DESCR,ALIAS_VALOR,DESCRICAO,FORMATO,GRUPO,MULTIEMP,OPCAO,SIS,SQL_LISTA,TAMANHO,TIPOALT,TIPO_VALOR,VALMAX,VALMIN,VALOR,VALOR_DEFAULT FROM HAD_OPCOES_ITENS WHERE 1=0 UNION ALL
SELECT 'Nome do destino', 'Destino', 'Destino para contagem de tempo nas simulações de aposentadoria', '', 'SIMULACAO', 'N', 'DESTINO_SIMUL_CONTA', 'RPrevAposent', 'select destino, nome from calculo_destinos where tipo_atendente = ''C'' and habilitado = ''S'' order by destino', TO_NUMBER('30'), TO_NUMBER('0'), 'V', TO_NUMBER(''), TO_NUMBER(''), '', '' FROM DUAL
) TEMP_20171101093012
WHERE (SIS,GRUPO,OPCAO) NOT IN
  (SELECT SIS,GRUPO,OPCAO FROM HAD_OPCOES_ITENS)
/
COMMIT;
EXEC EXEC_SQL_HADES('ALTER TABLE HAD_OPCOES_ITENS ENABLE ALL TRIGGERS')
SET SCAN ON

SET SCAN OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
EXEC EXEC_SQL_HADES('ALTER TABLE HAD_OPCOES_ITENS DISABLE ALL TRIGGERS')
INSERT INTO HAD_OPCOES_ITENS
(ALIAS_DESCR, ALIAS_VALOR, DESCRICAO, FORMATO, GRUPO, MULTIEMP, OPCAO, SIS, SQL_LISTA, TAMANHO, TIPOALT, TIPO_VALOR, VALMAX, VALMIN, VALOR, VALOR_DEFAULT)
SELECT * FROM (
SELECT ALIAS_DESCR,ALIAS_VALOR,DESCRICAO,FORMATO,GRUPO,MULTIEMP,OPCAO,SIS,SQL_LISTA,TAMANHO,TIPOALT,TIPO_VALOR,VALMAX,VALMIN,VALOR,VALOR_DEFAULT FROM HAD_OPCOES_ITENS WHERE 1=0 UNION ALL
SELECT '', '', 'Código do cargo para identificação do Presidente do Rio Previdência', '', 'RELATORIOS', 'N', 'CARGO_PRESIDENTE_RIOPREV', 'RPrevAposent', '', TO_NUMBER('6'), TO_NUMBER('0'), 'N', TO_NUMBER('999999'), TO_NUMBER('0'), '', '283201' FROM DUAL
) TEMP_20171117123726
WHERE (SIS,GRUPO,OPCAO) NOT IN
  (SELECT SIS,GRUPO,OPCAO FROM HAD_OPCOES_ITENS)
/
COMMIT;
EXEC EXEC_SQL_HADES('ALTER TABLE HAD_OPCOES_ITENS ENABLE ALL TRIGGERS')
SET SCAN ON