--
-- Cadastro do sistema 'RPrevAposent'
--
SET SCAN OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
EXEC EXEC_SQL_HADES('ALTER TABLE SISTEMA DISABLE ALL TRIGGERS')
INSERT INTO SISTEMA
(FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, HABILSIS, NOMESIS, SIS, TAKE, VERSAO)
SELECT * FROM (
SELECT FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,HABILSIS,NOMESIS,SIS,TAKE,VERSAO FROM SISTEMA WHERE 1=0 UNION ALL
SELECT '', '', '', '', '', '', '', '', '', '', 'S', 'Concessão de aposentadorias Rio Previdência', 'RPrevAposent', TO_DATE(''), '1.0' FROM DUAL
) TEMP_20170217084041
WHERE (SIS) NOT IN
  (SELECT SIS FROM SISTEMA)
/
COMMIT;
EXEC EXEC_SQL_HADES('ALTER TABLE SISTEMA ENABLE ALL TRIGGERS')
SET SCAN ON


--
-- Cadastros das transa??es do m?dulo
--

SET SCAN OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
EXEC EXEC_SQL_HADES('ALTER TABLE TRANSACAO DISABLE ALL TRIGGERS')
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0026', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0026', 'N', '', '', 'Parametrização tipos de Aposent. e Finalidades de Contagem', 'N', 'N', 'RPrevAposent', 'trpv0026' FROM DUAL
) TEMP_20170417160342
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
--INSERT INTO TRANSACAO
--(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
--SELECT * FROM (
--SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
--SELECT 'trpv0004', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0004', 'N', '', '', 'Parametrização de prazos entre passos', 'N', 'N', 'RPrevAposent', 'trpv0004' FROM DUAL
--) TEMP_20170417160342
--WHERE (SIS,TRANS) NOT IN
--  (SELECT SIS,TRANS FROM TRANSACAO)
--/
--COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0025', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0025', 'N', '', '', 'Parametrização de rubricas para fixação de proventos', 'N', 'N', 'RPrevAposent', 'trpv0025' FROM DUAL
) TEMP_20170417160342
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
--INSERT INTO TRANSACAO
--(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
--SELECT * FROM (
--SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
--SELECT 'trpv0001', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0001', 'N', '', '', 'Manutenção de passos', 'N', 'N', 'RPrevAposent', 'trpv0001' FROM DUAL
--) TEMP_20170530152551
--WHERE (SIS,TRANS) NOT IN
--  (SELECT SIS,TRANS FROM TRANSACAO)
--/
--COMMIT;
--INSERT INTO TRANSACAO
--(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
--SELECT * FROM (
--SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
--SELECT 'trpv0002', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0002', 'N', '', '', 'Parametrização de sequências de mudança de passos', 'N', 'N', 'RPrevAposent', 'trpv0002' FROM DUAL
--) TEMP_20170530154343
--WHERE (SIS,TRANS) NOT IN
--  (SELECT SIS,TRANS FROM TRANSACAO)
--/
--COMMIT;
--INSERT INTO TRANSACAO
--(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
--SELECT * FROM (
--SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
<<<<<<< HEAD
--SELECT 'trpv0003', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0003', 'N', '', '', 'P?gina de teste de acesso p�blica - 003', 'S', 'N', 'RPrevAposent', 'trpv0003' FROM DUAL
=======
--SELECT 'trpv0003', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0003', 'N', '', '', 'P?gina de teste de acesso pública - 003', 'S', 'N', 'RPrevAposent', 'trpv0003' FROM DUAL
>>>>>>> origin/develop
--) TEMP_20170417160342
--WHERE (SIS,TRANS) NOT IN
--  (SELECT SIS,TRANS FROM TRANSACAO)
--/
--COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0007', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0007', 'N', '', '', 'Padrões de acesso', 'N', 'N', 'RPrevAposent', 'trpv0007' FROM DUAL
) TEMP_20170417160342
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0023', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0023', 'N', '', '', 'Parametrização de frequências que contam', 'N', 'N', 'RPrevAposent', 'trpv0023' FROM DUAL
) TEMP_20170417160342
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0017', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0017', 'N', '', '', 'Parametrização de valores auxiliares', 'N', 'N', 'RPrevAposent', 'trpv0017' FROM DUAL
) TEMP_20170417160342
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
--INSERT INTO TRANSACAOasdasdsa
--(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
--SELECT * FROM (
--SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
--SELECT 'trpv0018', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0018', 'N', '', '', 'Manutenção da lista de documentos', 'N', 'N', 'RPrevAposent', 'trpv0018' FROM DUAL
--) TEMP_20170417160342
--WHERE (SIS,TRANS) NOT IN
--  (SELECT SIS,TRANS FROM TRANSACAO)
--/
--COMMIT;
--INSERT INTO TRANSACAO
--(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
--SELECT * FROM (
--SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
--SELECT 'trpv0019', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0019', 'N', '', '', 'Parametrização de contagem para finalid. de aposentadoria', 'N', 'N', 'RPrevAposent', 'trpv0019' FROM DUAL
--) TEMP_20170417160342
--WHERE (SIS,TRANS) NOT IN
--  (SELECT SIS,TRANS FROM TRANSACAO)
--/
--COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0028', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0028', 'N', '', '', 'Consulta contribuições previdenciárias', 'N', '', 'RPrevAposent', 'trpv0028' FROM DUAL
) TEMP_20170518182237
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0030', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0030', 'N', '', '', 'Consulta das atividades do exercício do vínculo', 'N', 'N', 'RPrevAposent', 'trpv0030' FROM DUAL
) TEMP_20170417160342
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0034', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0034', 'N', '', '', 'Consulta de licenças prêmio do vínculo', 'N', 'N', 'RPrevAposent', 'trpv0034' FROM DUAL
) TEMP_20170529181139
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0037', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0037', 'N', '', '', 'Consulta pré-contagem de finalidades de aposentadoria', 'N', 'N', 'RPrevAposent', 'trpv0037' FROM DUAL
) TEMP_20170417160342
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0031', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0031', 'N', '', '', 'Consulta das averbações do vínculo', 'N', 'N', 'RPrevAposent', 'trpv0031' FROM DUAL
) TEMP_20170417160342
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0036', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0036', 'N', '', '', 'Consulta eventos do vínculo', 'N', 'N', 'RPrevAposent', 'trpv0036' FROM DUAL
) TEMP_20170417160342
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0032', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0032', 'N', '', '', 'Consulta das cessões externas do vínculo', 'N', 'N', 'RPrevAposent', 'trpv0032' FROM DUAL
) TEMP_20170417160342
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
--INSERT INTO TRANSACAO
--(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
--SELECT * FROM (
--SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
--SELECT 'trpv0014', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0014', 'N', '', '', 'Parametrização de checklists de documentos', 'N', 'N', 'RPrevAposent', 'trpv0014' FROM DUAL
--) TEMP_20170417160342
--WHERE (SIS,TRANS) NOT IN
--  (SELECT SIS,TRANS FROM TRANSACAO)
--/
--COMMIT;
--INSERT INTO TRANSACAO
--(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
--SELECT * FROM (
--SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
--SELECT 'trpv0015', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0015', 'N', '', '', 'Parametrização de tipos de requerimento', 'N', 'N', 'RPrevAposent', 'trpv0015' FROM DUAL
--) TEMP_20170417160342
--WHERE (SIS,TRANS) NOT IN
--  (SELECT SIS,TRANS FROM TRANSACAO)
--/
--COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0033', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0033', 'N', '', '', 'Consulta das frequências do vínculo', 'N', 'N', 'RPrevAposent', 'trpv0033' FROM DUAL
) TEMP_20170417160342
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0039', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0039', 'N', '', '', 'Consulta consignações do servidor', 'N', 'N', 'RPrevAposent', 'trpv0039' FROM DUAL
) TEMP_20170417160342
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;

INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0027', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0027', 'N', '', '', 'Contribuições individuais e suplementares', 'N', 'N', 'RPrevAposent', 'trpv0027' FROM DUAL
) TEMP_20170417160342
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0029', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0029', 'N', '', '', 'Cadastro de descontos de tempo referentes a períodos', 'N', 'N', 'RPrevAposent', 'trpv0029' FROM DUAL
) TEMP_20170417160342
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0005', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0005', 'N', '', '', 'Atualização de dados banc?rios do vínculo inativo', 'N', 'N', 'RPrevAposent', 'trpv0005' FROM DUAL
) TEMP_20170518182414
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0011', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0011', 'N', '', '', 'Cadastro de usuários do módulo de concessão', 'N', 'N', 'RPrevAposent', 'trpv0011' FROM DUAL
) TEMP_20170417160342
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
/
COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0012', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0012', 'N', '', '', 'Manutenção de eventos inativos', 'N', 'N', 'RPrevAposent', 'trpv0012' FROM DUAL
) TEMP_20170417160342
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0035', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0035', 'N', '', '', 'Consulta atributos do  vínculo', 'N', 'N', 'RPrevAposent', 'trpv0035' FROM DUAL
) TEMP_20170417160342
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0038', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0038', 'N', '', '', 'Consulta dos dependentes e pensões alimentícias do vínculo', 'N', 'N', 'RPrevAposent', 'trpv0038' FROM DUAL
) TEMP_20170417160342
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0045', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0045', 'N', '', '', 'Editar dados pessoais de servidores inativos', 'N', '', 'RPrevAposent', 'trpv0045' FROM DUAL
) TEMP_20170612093912
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0006', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0006', 'N', '', '', 'Documentos legais e referências', 'N', 'N', 'RPrevAposent', 'trpv0006' FROM DUAL
) TEMP_20170417160342
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0048', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0048', 'N', '', '', 'Regras de pensão alimentícia', 'N', 'N', 'RPrevAposent', 'trpv0048' FROM DUAL
) TEMP_20170417160342
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0009', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0009', 'N', '', '', 'Simulação de aposentadoria', 'N', 'N', 'RPrevAposent', 'trpv0009' FROM DUAL
) TEMP_20170417160342
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
--INSERT INTO TRANSACAO
--(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
--SELECT * FROM (
--SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
--SELECT 'trpv0010', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0010', 'N', '', '', 'Consulta histórico de mudança de passos do requerimento', 'N', 'N', 'RPrevAposent', 'trpv0010' FROM DUAL
--) TEMP_20170417160342
--WHERE (SIS,TRANS) NOT IN
--  (SELECT SIS,TRANS FROM TRANSACAO)
--/
--COMMIT;
--INSERT INTO TRANSACAO
--(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
--SELECT * FROM (
--SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
--SELECT 'trpv0022', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0022', 'N', '', '', 'Agendar requerimento', 'N', 'N', 'RPrevAposent', 'trpv0022' FROM DUAL
--) TEMP_20170417160342
--WHERE (SIS,TRANS) NOT IN
--  (SELECT SIS,TRANS FROM TRANSACAO)
--/
--COMMIT;
--INSERT INTO TRANSACAO
--(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
--SELECT * FROM (
--SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
--SELECT 'trpv0008', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0008', 'N', '', '', 'Consulta requerimentos do servidor', 'N', 'N', 'RPrevAposent', 'trpv0008' FROM DUAL
--) TEMP_20170417160342
--WHERE (SIS,TRANS) NOT IN
--  (SELECT SIS,TRANS FROM TRANSACAO)
--/
--COMMIT;
--INSERT INTO TRANSACAO
--(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
--SELECT * FROM (
--SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
--SELECT 'trpv0020', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0020', 'N', '', '', 'Consulta requerimentos por passo', 'N', 'N', 'RPrevAposent', 'trpv0020' FROM DUAL
--) TEMP_20170417160342
--WHERE (SIS,TRANS) NOT IN
--  (SELECT SIS,TRANS FROM TRANSACAO)
--/
--COMMIT;
--INSERT INTO TRANSACAO
--(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
--SELECT * FROM (
--SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
--SELECT 'trpv0024', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0024', 'N', '', '', 'Reversão do último passo do requerimento', 'N', 'N', 'RPrevAposent', 'trpv0024' FROM DUAL
--) TEMP_20170417160342
--WHERE (SIS,TRANS) NOT IN
--  (SELECT SIS,TRANS FROM TRANSACAO)
--/
--COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0021', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0021', 'N', '', '', 'Parametrização de contagem para finalid. de aposentadoria', 'N', 'N', 'RPrevAposent', 'trpv0021' FROM DUAL
) TEMP_20170417160342
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0057', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0057', 'N', '', '', 'Lançamento manual de movimentação em folha', 'N', 'N', 'RPrevAposent', 'trpv0057' FROM DUAL
) TEMP_20170417160342
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0059', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0059', 'N', '', '', 'Permissão para atributos de inativos', 'N', 'N', 'RPrevAposent', 'trpv0059' FROM DUAL
) TEMP_20170417160342
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0050', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0050', 'N', '', '', 'Aposentados por tipo aposent. e plano previdenciário', 'N', 'N', 'RPrevAposent', 'trpv0050' FROM DUAL
) TEMP_20170417160342
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0052', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0052', 'N', '', '', 'Gráfico de aposentados por sexo e tipo de aposentadoria', 'N', 'N', 'RPrevAposent', 'trpv0052' FROM DUAL
) TEMP_20170417160342
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0053', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0053', 'N', '', '', 'Gráfico de aposentados por tipo de aposentadoria', 'N', 'N', 'RPrevAposent', 'trpv0053' FROM DUAL
) TEMP_20170417160342
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0044', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0044', 'N', '', '', 'Verificação de regularidade previdenciária', 'N', 'N', 'RPrevAposent', 'trpv0044' FROM DUAL
) TEMP_20170417160342
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0056', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0056', 'N', '', '', 'Atributos de inativos', 'N', 'N', 'RPrevAposent', 'trpv0056' FROM DUAL
) TEMP_20170417160342
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0042', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0042', 'N', '', '', 'Dados aposentadoria do servidor', 'N', 'N', 'RPrevAposent', 'trpv0042' FROM DUAL
) TEMP_20170417160342
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;

INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0047', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0047', 'N', '', '', 'Editar dados pessoais de dependentes de servidores inativos', 'N', 'N', 'RPrevAposent', 'trpv0047' FROM DUAL
) TEMP_20170417160342
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0046', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0046', 'N', '', '', 'Certidões', 'N', 'N', 'RPrevAposent', 'trpv0046' FROM DUAL
) TEMP_20170417160342
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0058', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0058', 'N', '', '', 'Cadastrar representantes legais', 'N', 'N', 'RPrevAposent', 'trpv0058' FROM DUAL
) TEMP_20170417160342
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;
INSERT INTO TRANSACAO
(CHAVE, FLEX_CAMPO_01, FLEX_CAMPO_02, FLEX_CAMPO_03, FLEX_CAMPO_04, FLEX_CAMPO_05, FLEX_CAMPO_06, FLEX_CAMPO_07, FLEX_CAMPO_08, FLEX_CAMPO_09, FLEX_CAMPO_10, FORMTRANS, FORMTRANSCUST, ITEMMENU, LOGGING, NOMENOMENU, NOMEREDUZIDO, NOMETRANS, PUBLICATRANS, QRY_POS_ROLLBACK, SIS, TRANS)
SELECT * FROM (
SELECT CHAVE,FLEX_CAMPO_01,FLEX_CAMPO_02,FLEX_CAMPO_03,FLEX_CAMPO_04,FLEX_CAMPO_05,FLEX_CAMPO_06,FLEX_CAMPO_07,FLEX_CAMPO_08,FLEX_CAMPO_09,FLEX_CAMPO_10,FORMTRANS,FORMTRANSCUST,ITEMMENU,LOGGING,NOMENOMENU,NOMEREDUZIDO,NOMETRANS,PUBLICATRANS,QRY_POS_ROLLBACK,SIS,TRANS FROM TRANSACAO WHERE 1=0 UNION ALL
SELECT 'trpv0058', '', '', '', '', '', '', '', '', '', '', '', '', 'trpv0058', 'N', '', '', 'Cadastrar representantes legais', 'N', 'N', 'RPrevAposent', 'trpv0058' FROM DUAL
) TEMP_20170417160342
WHERE (SIS,TRANS) NOT IN
  (SELECT SIS,TRANS FROM TRANSACAO)
/
COMMIT;

EXEC EXEC_SQL_HADES('ALTER TABLE TRANSACAO ENABLE ALL TRIGGERS')
SET SCAN ON
