CREATE OR REPLACE FORCE VIEW CERG_VW_SIMULA_APOSENT AS
  SELECT ANOSAPOS
  , ANOSTRAB
  , DIASTRAB
  , DTFIM
  , DTINI
  , DT_HOMOLOG
  , FUNDAMENTO
  , GRUPO
  , FRACAO1
  , FRACAO2
  , NUMFUNC
  , NUMVINC
  , TIPOAPOS
  , FINALIDADE
  , TIPO_CALCULO_APOS
  , VALOR_MEDIA
  , CHAVE_CONTAGEM
  , EH_PROPORCIONAL
  , PONTLEI
  , ID_SIMULACAO
  , ID
  FROM cerg_simula_aposent
  WHERE ID_SIMULACAO = tgrj_pack_folha.get_id_simulacao_apos ()
/
